services:
  postgres:
    extends:
      file: infrastructure/docker/docker-compose.base.yml
      service: postgres

  ceitba-api-prod:
    extends:
      file: infrastructure/docker/docker-compose.prod.yml
      service: ceitba-api-prod

volumes:
  postgres_data:
    driver: local

networks:
  ceitba-network:
    driver: bridge
