// User Domain Tokens
export const USER_REPOSITORY = "USER_REPOSITORY";

// ITBA Domain Tokens
export const CAREER_REPOSITORY = "CAREER_REPOSITORY";
export const CLASSROOM_REPOSITORY = "CLASSROOM_REPOSITORY";
export const SUBJECT_REPOSITORY = "SUBJECT_REPOSITORY";
export const SUBJECT_PLAN_REPOSITORY = "SUBJECT_PLAN_REPOSITORY";
export const COMMISSION_REPOSITORY = "COMMISSION_REPOSITORY";
export const ITBA_API_SERVICE = "ITBA_API_SERVICE";
