// User Domain Tokens
export const USER_REPOSITORY = "USER_REPOSITORY";

// Career Domain - Repository Tokens
export const CAREER_REPOSITORY = "CAREER_REPOSITORY";
export const CLASSROOM_REPOSITORY = "CLASSROOM_REPOSITORY";
export const SUBJECT_REPOSITORY = "SUBJECT_REPOSITORY";
export const SUBJECT_PLAN_REPOSITORY = "SUBJECT_PLAN_REPOSITORY";
export const COMMISSION_REPOSITORY = "COMMISSION_REPOSITORY";
export const ITBA_API_SERVICE = "ITBA_API_SERVICE";

// Career Domain - Service Tokens
export const CAREER_SERVICE = "CAREER_SERVICE";
export const CLASSROOM_SERVICE = "CLASSROOM_SERVICE";
export const SUBJECT_SERVICE = "SUBJECT_SERVICE";
export const SUBJECT_PLAN_SERVICE = "SUBJECT_PLAN_SERVICE";
export const COMMISSION_SERVICE = "COMMISSION_SERVICE";
