export enum Branch {
    IT = "IT",
    MEDIA = "MEDIA",
    INFRA = "INFRA",
    DEPORTES = "DEPORTES",
    NAUTICA = "NAUTICA",
    EVENTOS = "EVENTOS",
    DIRECTIVOS = "DIRECTIVOS"
}

export enum StaffType {
    PRESIDENTE = "PRESIDENTE",
    VICEPRESIDENTE = "VICEPRESIDENTE",
    SECRETARIA = "SECRETARIA",
    TESORERIA = "TESORERIA",
    LIDER = "LIDER",
    MIEMBRO = "MIEMBRO"
}